version: "3.3"
services:
  app:
    container_name: vidby_api
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - "8001:8080"
    volumes:
      - .:/app
      - ./content:/app/content
    depends_on:
      - vidby_postgresdb

  vidby_postgresdb:
    image: postgres:latest
    container_name: vidby_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'